{%raw%}---
- name: Create webpack stats file
  command: touch webpack-stats.json
  become: false
  tags: ['deploy']

- name: Run build webpack
  command: {{ webpack_path }} --config {{ webpack_config }} --progress --colors
  become: false
  tags: ['deploy']

- name: collect static
  django_manage: command="collectstatic -i js -i css -i server.js -i webpack.base.config.js -i webpack.dev.config.js -i webpack.prod.config.js" app_path={{ project_path }} virtualenv={{ venv_path }}
  become: false
  tags: ['deploy']
{%endraw%}
